var localize = {
    "en-US": {
        "library": "BlueStacks 4.240.30 Lite - Hieu GL Lite",
        "allInstalled": "All Apps",
        "bluestacksApps": "BlueStacks apps",
        "blog": "Blog",
        "systemApps": "System apps",
        "installApk": "Install APK",
        "deleteApps": "Delete apps",
        "delete": "Delete",
        "cancel": "Cancel",
        "installingApp": "Installing app",
        "newApp": "New app",
        "installFailed": "Install failed",
        "retry": "Retry",
        "reload": "Reload",
        "addmusic": "Add Music",
        "play": "PLAY MUSIC",
        "pause": "PAUSE MUSIC"
    },
    "vi-VN": {
        "library": "BlueStacks 4.240.30 Lite - Hiếu GL Lite",
        "allInstalled": "Tất cả ứng dụng",
        "bluestacksApps": "Các ứng dụng BlueStacks",
        "blog": "Blog",
        "systemApps": "Ứng dụng hệ thống",
        "installApk": "Cài đặt APK",
        "deleteApps": "Xóa ứng dụng",
        "delete": "Xóa",
        "cancel": "Hủy bỏ",
        "installingApp": "Đang cài đặt",
        "newApp": "Mới!",
        "installFailed": "Cài đặt thất bại",
        "retry": "Thử lại",
        "reload": "Tải lại",
        "reload": "Reload",
        "addmusic": "Thêm nhạc",
        "play": "PHÁT NHẠC",
        "pause": "TẠM DỪNG NHẠC"
    },
    "th-TH": {
        "library": "BlueStacks 4.240.30 Lite - Hieu GL Lite",
        "allInstalled": "All installed",
        "bluestacksApps": "Bluestacks apps",
        "blog": "Blog",
        "systemApps": "System apps",
        "installApk": "ติดตั้ง APK",
        "deleteApps": "ลบแอป",
        "delete": "ลบ",
        "cancel": "ยกเลิก",
        "areYouSure": "คุณแน่ใจหรือไม่ว่าต้องการถอนการติดตั้งแอพที่เลือก ข้อมูลทั้งหมดจะถูกลบ",
        "installingApp": "กำลังติดตั้ง App",
        "newApp": "New app",
        "installFailed": "ติดตั้งล้มเหลว",
        "retry": "ลองใหม่อีกครั้ง",
        "reload": "รีเฟรช"
    },
    "ru-RU": {
        "library": "BlueStacks 4.240.30 Lite - Hieu GL Lite",
        "allInstalled": "Установлено",
        "bluestacksApps": "Приложения BlueStacks",
        "blog": "Блог",
        "systemApps": "Системные приложения",
        "installApk": "Установить APK",
        "deleteApps": "Удалить приложения",
        "delete": "Удалить",
        "cancel": "Отменить",
        "areYouSure": "Вы уверены, что желаете удалить выбранное приложение? Вы можете потерять несохраненные игровые данные.",
        "installingApp": "Устанавливаем приложение",
        "newApp": "Новое приложение",
        "installFailed": "Установка не удалась",
        "retry": "Повторить",
        "reload": "Обновить"
    }
}